{{- $name := .Values.store.mongodb.name }}
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
spec:
  members: 1
  type: ReplicaSet
  version: "5.0.32"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: hyperdx
      db: hyperdx
      passwordSecretRef:
        name: {{ $name }}-password
      roles:
        - name: dbOwner
          db: hyperdx
        - name: clusterMonitor
          db: admin
      scramCredentialsSecretName: {{ $name }}-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
