apiVersion: v1
kind: Service
metadata:
  name: grafana-ui
  namespace: {{ .Release.Namespace }}
  annotations:
    lbipam.cilium.io/ips: {{ .Values.global.grafanaAddress | quote }}
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: grafana
  selector:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: {{ .Release.Name }}
