apiVersion: v1
kind: Service
metadata:
  name: hyperdx-ui
  namespace: {{ .Release.Namespace }}
  annotations:
    lbipam.cilium.io/ips: {{ .Values.global.hyperdxAddress | quote }}
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.clickstack.hyperdx.ports.app | default 3000 }}
  selector:
    app.kubernetes.io/name: clickstack
    app.kubernetes.io/instance: {{ .Release.Name }}
    app: {{ .Values.clickstack.fullnameOverride }}
