apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.awsCredentials.secretName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: {{ .Values.awsCredentials.refreshInterval }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: {{ .Values.awsCredentials.secretName }}
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: AUTOSCALER_AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: AUTOSCALER_AWS_SECRET_ACCESS_KEY
