apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.longhorn.defaultBackupStore.backupTargetCredentialSecret }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.backupCredentials.refreshInterval }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: {{ .Values.longhorn.defaultBackupStore.backupTargetCredentialSecret }}
  data:
    - secretKey: AWS_ENDPOINTS
      remoteRef:
        key: LONGHORN_AWS_ENDPOINTS
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: LONGHORN_AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: LONGHORN_AWS_SECRET_ACCESS_KEY
