apiVersion: v2
name: platform-argo-cd
description: argo-cd wrapper
type: application
version: 0.1.0
dependencies:
  - name: argo-cd
    version: "9.7.1"
    repository: https://argoproj.github.io/argo-helm
