apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: otel-agent-token
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.secrets.refreshInterval }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: otel-agent-token
  data:
    - secretKey: token
      remoteRef:
        key: OTEL_INGEST_TOKEN
