repoURL: https://github.com/phuchoang2603/talos-proxmox.git
targetRevision: main
cluster: dev
components:
  burst-policy:
    path: apps/components/burst-policy
    namespace: kube-system
    syncWave: "-1"
    releaseName: burst-policy
  cluster-autoscaler:
    path: apps/components/cluster-autoscaler
    namespace: cluster-autoscaler
    syncWave: "0"
    releaseName: cluster-autoscaler
    valueFilesByCluster:
      prod:
        - environments/prod/values.yaml
  argo-rollouts:
    path: apps/components/argo-rollouts
    namespace: argo-rollouts
    syncWave: "-1"
    releaseName: argo-rollouts
    valueFilesByCluster:
      dev:
        - environments/dev/values.yaml
      prod:
        - environments/prod/values.yaml
  external-secrets:
    path: apps/components/external-secrets
    namespace: operators
    syncWave: "0"
    releaseName: external-secrets
  cnpg:
    path: apps/components/cnpg
    namespace: operators
    syncWave: "0"
    releaseName: cnpg
  strimzi:
    path: apps/components/strimzi
    namespace: operators
    syncWave: "0"
    releaseName: strimzi-cluster-operator
  mongodb-operator:
    path: apps/components/mongodb
    namespace: operators
    syncWave: "0"
    releaseName: mongodb-operator
  observability:
    path: apps/components/observability
    releaseName: observability
    namespace: monitoring
    syncWave: "1"
    valueFilesByCluster:
      prod:
        - environments/prod/values.yaml
    ignoreDifferences: true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/warn: privileged
  cloudflare-tunnel:
    path: apps/components/cloudflare-tunnel
    releaseName: cloudflare-tunnel
    namespace: cloudflare-tunnel
    syncWave: "2"
    valueFilesByCluster:
      prod:
        - environments/prod/values.yaml
