loadBalancerIPPool:
  blocks:
    - start: "10.69.12.128"
      stop: "10.69.12.254"

l2Announcement:
  nodes: [prod-server1, prod-server2, prod-server3, prod-longhorn1, prod-longhorn2, prod-longhorn3]
