driver:
  enabled: false
toolkit:
  enabled: false
devicePlugin:
  enabled: false
hostPaths:
  driverInstallDir: /usr/local
cdi:
  enabled: true
clusterPolicy:
  deployCR: true
gpuCluster:
  deployCR: false
