apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dex-config
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.secrets.refreshInterval }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: dex-config
    template:
      engineVersion: v2
      data:
        config.yaml: |
          issuer: {{ .Values.identity.issuer }}
          storage:
            type: kubernetes
            config:
              inCluster: true
          web:
            http: 0.0.0.0:5556
          oauth2:
            skipApprovalScreen: true
          enablePasswordDB: true
          staticPasswords:
            - email: {{ .Values.identity.email }}
              hash: {{ `"{{ .passwordHash }}"` }}
              username: user
              userID: "15841185641784"
          staticClients:
            - id: kubeflow-oidc-authservice
              name: Kubeflow
              secret: {{ `"{{ .clientSecret }}"` }}
              redirectURIs:
                - {{ .Values.identity.redirectURI }}
            - id: grafana
              name: Grafana
              secret: {{ `"{{ .grafanaClientSecret }}"` }}
              redirectURIs:
                - {{ .Values.identity.grafanaRedirectURI }}
  data:
    - secretKey: passwordHash
      remoteRef:
        key: AUTH_DEX_PASSWORD_BCRYPT
    - secretKey: clientSecret
      remoteRef:
        key: AUTH_OIDC_CLIENT_SECRET
    - secretKey: grafanaClientSecret
      remoteRef:
        key: GRAFANA_OIDC_CLIENT_SECRET
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-credentials
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.secrets.refreshInterval }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: oauth2-proxy-credentials
    template:
      engineVersion: v2
      data:
        client-id: kubeflow-oidc-authservice
        client-secret: {{ `"{{ .clientSecret }}"` }}
        cookie-secret: {{ `"{{ .cookieSecret }}"` }}
  data:
    - secretKey: clientSecret
      remoteRef:
        key: AUTH_OIDC_CLIENT_SECRET
    - secretKey: cookieSecret
      remoteRef:
        key: AUTH_OAUTH2_COOKIE_SECRET
