# The read-only token Secret is created by the platform OpenTofu root, not Argo CD.
dopplerToken:
  namespace: kube-system
  name: doppler-token
  key: dopplerToken

external-secrets:
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
  webhook:
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi
  certController:
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi
