apiVersion: v1
kind: ConfigMap
metadata:
  name: artifact-repositories
  namespace: kubeflow
  annotations:
    workflows.argoproj.io/default-artifact-repository: default-v1
data:
  default-v1: |
    archiveLogs: true
    s3:
      endpoint: minio.home.phuchoang.sbs:443
      bucket: kubeflow-prod-pipelines
      insecure: false
      keyFormat: "private-artifacts/{{`{{workflow.namespace}}`}}/{{`{{workflow.name}}`}}/{{`{{pod.name}}`}}"
      accessKeySecret:
        name: mlpipeline-minio-artifact
        key: accesskey
      secretKeySecret:
        name: mlpipeline-minio-artifact
        key: secretkey
