apiVersion: v2
name: platform-kubeflow
description: Prod Kubeflow components without shared infrastructure or authentication services
type: application
version: 0.1.0
dependencies:
  - name: spark-operator
    version: 2.5.2
    repository: https://kubeflow.github.io/spark-operator
    condition: spark-operator.enabled
