apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-dev
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: talos-proxmox
  source:
    repoURL: https://github.com/phuchoang2603/talos-proxmox.git
    targetRevision: main
    path: apps/argocd/platform
    helm:
      parameters:
        - name: cluster
          value: dev
        - name: targetRevision
          value: $ARGOCD_APP_SOURCE_TARGET_REVISION
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
